// "use client";
import "./globals.css";
import "./tv1.css";
import CalendarHeader from "./diary/CalendarHeader";

export const metadata = {
  title: "Emotional Diary",
  description: "Generated by LDB",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="vertical-align">
          <CalendarHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
